version: '3.3'
volumes:
  data:
services:
  slim_app:
    container_name: slim_app
    volumes:
      - "./:/var/www"
      - "/var/www/node_modules"
      - "/var/www/vendor"
    build: .
    command: ["php", "-S", "0.0.0.0:8080" ]
    ports:
      - "80:8080"